spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    #hibernate:
      #ddl-auto: update
  thymeleaf:
    prefix: /WEB-INF/view/
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
